<!ELEMENT TRIAL (DOMAIN, STRING-DESCRIPTION, DESCRIPTION, ATTRIBUTE-SET)>
<!ELEMENT DOMAIN (ENTITY)+>
<!ELEMENT DET (#PCDATA)>
<!ELEMENT STRING-DESCRIPTION (#PCDATA)>
<!ELEMENT DESCRIPTION (#PCDATA|DET|ATTRIBUTE|META-ATTRIBUTE|DESCRIPTION)*>
<!ELEMENT ATTRIBUTE-SET (ATTRIBUTE)+>
<!ELEMENT ENTITY (ATTRIBUTE)+>
<!ELEMENT ATTRIBUTE (#PCDATA)*>
<!ELEMENT META-ATTRIBUTE (#PCDATA|ATTRIBUTE)*>

<!ATTLIST DET
	ID CDATA #REQUIRED
	VALUE (definite|indefinite|numeral|other) #REQUIRED>

<!ATTLIST DESCRIPTION
	NUM (singular|plural) #REQUIRED >

<!ATTLIST TRIAL 
	CARDINALITY (1|2) #REQUIRED
	SIMILARITY (similar|dissimilar) #REQUIRED
	CONDITION CDATA #REQUIRED 
	DOMAIN (furniture|people) #REQUIRED
	ID CDATA #REQUIRED>
	

<!ATTLIST ATTRIBUTE
	POLARITY (neg) #IMPLIED
	NAME (type|colour|orientation|size|x-dimension|y-dimension|other) #REQUIRED
	VALUE (chair|sofa|desk|fan|red|green|blue|grey|
			large|small|front|left|
			right|back|0|1|2|3|4|5|unknown|other) #REQUIRED
	TYPE (literal|boolean|gradable) #IMPLIED
	ID CDATA #IMPLIED>
	
<!ATTLIST META-ATTRIBUTE
	NAME CDATA #FIXED "location"
	ID CDATA #REQUIRED
	VALUE (top|bottom|left|right|middle|other) #REQUIRED
	REL CDATA #IMPLIED>
	
<!ATTLIST ENTITY
	ID CDATA #REQUIRED
	IMAGE CDATA #REQUIRED
	TYPE (target|distractor) #REQUIRED>
